const String appUrl = "https://ednruyxcytmxfounwodq.supabase.co";
const String appKey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkbnJ1eXhjeXRteGZvdW53b2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjkxMDMxMDMsImV4cCI6MjA0NDY3OTEwM30.qHxnt4-2XEEo6rlqzzvgDh5avvtLfR3owzjNqWyX5xY";
